Improve readme, add more wiki links
php-webdriver/php-webdriver pull request #836
Opened 2020-11-25 17:31 UTC by OndraM

2020-11-25 18:49 UTC, williamdes approved these changes

2020-11-28 02:03 UTC, OndraM commented
Review from any native speaker would be greatly appreciated! :slightly_smiling_face: (Maybe @andrewnicols if you'd be able to find some time for this?)

2020-12-09 05:25 UTC, andrewnicols requested changes
Looks like a good set of updates. Just a few minor grammatical uggestions.

2020-12-09 05:25 UTC, andrewnicols commented on README.md
> +📙 Below you find only simple example, make sure to read our wiki for [more information on Chrome/Chromedriver](https://github.com/php-webdriver/php-webdriver/wiki/Chrome).
Minor grammatical suggestion:

Below you _will find a_ simple example. Make sure to read our wiki for more information.

2020-12-09 05:25 UTC, andrewnicols commented on README.md
> +in different browsers (like on your CI server) or eg. when you need to distribute tests amongst multiple machines
Selenium server can be useful when you need to execute multiple tests at once, when you run tests in several different browsers (like on your CI server), or when you need to distribute tests amongst several machines in grid mode (where one Selenium server acts as a hub, and others connect to it as nodes).

2020-12-09 05:25 UTC, andrewnicols commented on README.md
> +The latest version can be found on [Selenium download page](https://www.selenium.dev/downloads/).
... on _the_ Selenium download page.

2020-12-09 05:25 UTC, andrewnicols commented on README.md
> +Capabilities can also be used to [📙 configure proxy server](https://github.com/php-webdriver/php-webdriver/wiki/HowTo-Work-with-proxy) which the browser should use.
configure _a_ proxy server

2020-12-11 11:01 UTC, williamdes approved these changes

2020-12-11 14:35 UTC, OndraM commented
Thanks a lot @andrewnicols 👌.

2020-12-11 14:35 UTC, merged