proxy
php-webdriver/php-webdriver pull request #966
Opened 2022-02-10 16:01 UTC by tomazov

advanced request settings

2022-02-10 16:01 UTC, tomazov commented
advanced request settings

2022-02-16 09:15 UTC, williamdes commented on lib/Remote/HttpCommandExecutor.php
> +        unsewt($uri);
```suggestion
        unset($uri);
```

2022-02-16 09:16 UTC, williamdes commented on lib/Remote/HttpCommandExecutor.php
>       * @param int|null $http_proxy_port
```suggestion
     * @param int|null $http_proxy_port
     * @param string|null $http_proxy_user
     * @param string|null $http_proxy_pass
```

2022-08-30 14:05 UTC, OndraM requested changes
While I can imagine there is possibility someone would run remote end behind a proxy, this PR is not even lintable... @tomazov Are you willing to finish the PR? If so, please:

1) Rebase the branch with current main branch
2) Address the comments in PR

Thanks!

2022-08-30 14:05 UTC, OndraM commented on lib/Remote/HttpCommandExecutor.php
> +        unsewt($uri);
I would remove this whole part of parsing URI. If someone needs this (which would be very uncommon case), they can do this parsing themselves and provide the values directly.

2022-09-15 21:32 UTC, closed without merging